### ISSUE TITLE
Proxy error shouldn't cause server to exit..

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/upholstery#12]
If there is a temporary issue with CouchDB (such as a high number of requests), this causes Upholstery to exit rather than only give an error.

```
root@gouda:/etc/canadiana/upholstery# docker-compose ps
         Name                Command       State    Ports
---------------------------------------------------------
upholstery_upholstery_1   yarn run start   Exit 1        
root@gouda:/etc/canadiana/upholstery# docker logs upholstery_upholstery_1
yarn run v1.13.0
$ node .
/upholstery/node_modules/http-proxy/lib/http-proxy/index.js:120
    throw err;
    ^

Error: connect ECONNREFUSED 10.202.1.11:5984
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@gouda:/etc/canadiana/upholstery# 

```

**Comment by SaschaAdler** [comment]
Sorted this out with a simple error catch that writes errors to stdout. Works when I use a bad Couch address; not sure about if the requests are flooding Couch.

**Comment by RussellMcOrmond** [comment]
Error catch is working.  The following is a timeout when a view hadn't been updated recently.

```
root@gouda:/etc/canadiana/upholstery# docker-compose logs -f
Attaching to upholstery_upholstery_1
upholstery_1  | yarn run v1.13.0
upholstery_1  | $ node .
upholstery_1  | { Error: socket hang up
upholstery_1  |     at createHangUpError (_http_client.js:323:15)
upholstery_1  |     at Socket.socketCloseListener (_http_client.js:364:25)
upholstery_1  |     at Socket.emit (events.js:194:15)
upholstery_1  |     at TCP._handle.close (net.js:597:12) code: 'ECONNRESET' }
upholstery_1  | { Error: socket hang up
upholstery_1  |     at createHangUpError (_http_client.js:323:15)
upholstery_1  |     at Socket.socketCloseListener (_http_client.js:364:25)
upholstery_1  |     at Socket.emit (events.js:194:15)
upholstery_1  |     at TCP._handle.close (net.js:597:12) code: 'ECONNRESET' }
upholstery_1  | { Error: socket hang up
upholstery_1  |     at createHangUpError (_http_client.js:323:15)
upholstery_1  |     at Socket.socketCloseListener (_http_client.js:364:25)
upholstery_1  |     at Socket.emit (events.js:194:15)
upholstery_1  |     at TCP._handle.close (net.js:597:12) code: 'ECONNRESET' }

```
